# Generated by Django 3.1 on 2020-09-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200902_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersad',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
