# Generated by Django 3.1 on 2020-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20200902_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersad',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
