# Generated by Django 3.1 on 2020-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offersad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersad',
            name='category',
            field=models.CharField(choices=[('hotel', 'hotel'), ('food', 'food'), ('activities', 'activities'), ('clothing', 'clothing'), ('items', 'items'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
