# Generated by Django 3.1 on 2020-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offersad_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersad',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
